name: $(MODULE_NAME)-$(date:yyyyMMdd)-$(rev:.r)
trigger: none
pr:
  branches:
    include:
      - refs/heads/main
  paths:
    include:
      - '**/*.tf'
      - '**/*.tf.json'
resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      name: Think-Cube/azure-devops-pipeline-templates
      ref: refs/heads/main
      endpoint: github.com
variables:
  - group: GITHUB-PAT-TOKEN
  - name: VM_IMAGE
    value: ubuntu-latest
  - name: MODULE_NAME
    value: "terraform-azure-application-insights"
stages:
  - template: azure-devops/templates/pipelines/validate_and_regenerate_doc_tf_module.yml@templates
    parameters:
      terraformVersion: 'latest'
      tfsecVersion: 'v1.26.0'
      allowTelemetryCollection: false
      terraformDocsVersion: 'v0.19.0'
      GithubRepo: 'Think-Cube/terraform-azure-application-insights'
      user_email: 'devops-bot@thinkcube.dev'
      user_name: 'DevOps Bot'