name: Generate terraform docs
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        working-dir: .
        output-file: README.md
        output-method: replace
        config-file: .terraform-docs.yml
        git-push: "true"
